# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc "A streaming JSON & YAML processor CLI tool"
  homepage "https://github.com/GeoffMall/flow"
  version "1.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GeoffMall/flow/releases/download/v1.4.2/flow_1.4.2_darwin_amd64.tar.gz"
      sha256 "e9267445f70028aca5bb6a3034fae17eda08d64b420675ac15d88238c64f2bc6"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GeoffMall/flow/releases/download/v1.4.2/flow_1.4.2_darwin_arm64.tar.gz"
      sha256 "b856c5ca9caa0381a4ed79c4cf01fee9cf65020badad6652335632e06f2662d5"

      def install
        bin.install "flow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GeoffMall/flow/releases/download/v1.4.2/flow_1.4.2_linux_amd64.tar.gz"
      sha256 "9e358b61c0f37891c0bbe9931bf612b7e7883c77c9fb52f983bae12d1fbc079a"
      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GeoffMall/flow/releases/download/v1.4.2/flow_1.4.2_linux_arm64.tar.gz"
      sha256 "82c3d24d6cc4a7093977e0d449c30b0bb867ebf0b1e182a119114e3f01435ec7"
      def install
        bin.install "flow"
      end
    end
  end

  test do
    system "#{bin}/flow", "--version"
  end
end
